import localFont from "next/font/local";
import "./globals.css";
import NavbarWrapper from "@/components/Navbar/NavbarWrapper";
import FooterContainer from "@/components/Footer/FooterContainer";
import { Providers } from "../redux/provider";
import { Poppins } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} ${poppins.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NavbarWrapper />
          {children}
          <FooterContainer />
        </Providers>
      </body>
    </html>
  );
}
